### ISSUE TITLE
please provide the IPs to verify the project

### ISSUE THREAD

**Issue by DGRamya** [airavata-courses/autobots#53]

**Comment by naveenkumarmarri** [comment]
The details of the client and server are documented on [ wiki page ](https://github.com/airavata-courses/autobots/wiki/CI---CD-on-Jetsream#continuous-deployment-1)

Also I triggered a fresh deployment to jetstream, can you try accessing server now, you should get a blank page instead of `ERR_CONNECTION_REFUSED`

**Comment by DGRamya** [comment]
for the following IP of TUS server http://129.114.16.133:8000/

" Cannot GET / " I am getting this error

**Comment by DGRamya** [comment]
Getting the following error for tus client

**Comment by naveenkumarmarri** [comment]
Can you try now?

**Comment by naveenkumarmarri** [comment]
> for the following IP of TUS server http://129.114.16.133:8000/
> 
> " Cannot GET / " I am getting this error

This isn't an error, in our case server is just for file hosting, so you can't see any front end app running there.

**Comment by DGRamya** [comment]
What are the steps to upload the file? Can I upload any file and specify the chunk size , is there any minimum requirement?

**Comment by naveenkumarmarri** [comment]
Yeah, you can upload any file of your choice, let it upload partially and close the tab . If you open again select the same file to upload, it should start from where it let off

**Comment by DGRamya** [comment]
@naveenkumarmarri If the server is not working please remove the link in wiki, it looks like failed scenario.
